import './css/globals.css'
import {ClusterProvider} from '@/components/cluster/cluster-data-access'
import {SolanaProvider} from '@/components/solana/solana-provider'
import {ReactQueryProvider} from './react-query-provider'
import { ChatbotWidget } from '@/components/ui/ChatbotWidget'

export const metadata = {
  title: 'Prototypecapsules',
  description: 'Generated by create-solana-dapp',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              {children}
              <ChatbotWidget />
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
